# Generated by Django 3.2.8 on 2021-11-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('image', models.TextField()),
                ('price', models.FloatField()),
                ('release_date', models.DateField()),
                ('lte_exists', models.TextField()),
                ('slug', models.CharField(max_length=80)),
            ],
        ),
    ]
